### PR TITLE
WIP: Update TLS for SECURITY-2290

### PR DESCRIPTION
**Pull request by mdiluz**
Update to the [v2.7.16](https://github.com/ARMmbed/mbedtls/tree/v2.7.16) (from v2.7.8) tag from upstream for SECURITY-2290.

Will recommend merging once testing has been handled.

### CODE REVIEW

**Comment by AndreasReich** [comment]
Wouldn't it be better to merge this into https://github.com/Unity-Technologies/mbedtls/tree/unity-mbedtls-2.7? We had some performance optimizations there that we tried to get upstream but didn't land (see https://github.com/ARMmbed/mbedtls/pull/1901). It could well be though that mbedtls is by now longer compatible with those or might have optimizations on their own.

**Comment by AndreasReich** [comment]
I'm not very concerned overall as we have native performance tests in Unity trunk that should catch it if we have a major regression :)

**Comment by mdiluz** [comment]
> Wouldn't it be better to merge this into https://github.com/Unity-Technologies/mbedtls/tree/unity-mbedtls-2.7?

That's a good point, I had assumed the default branch here was the one we were using on unity trunk, I've changed the base now. I'll need to re-do my tests on katana.

**Comment by mdiluz** [comment]
Actually, is the branch/merge model for this repo written up anywhere?

**Comment by AndreasReich** [comment]
> Actually, is the branch/merge model for this repo written up anywhere?

No, mostly because there was never an update ever since the work Valdemar (no longer at Unity) did. So I should rather say there is no branch/merge model since we only ever landed mbedtls once (or several times in a very short time period) as far as I know.

**Comment by mdiluz** [comment]
Fair enough, I've created a new PR #5 with a different base so the branch doesn't look quite so weird.

**Pull request closed without merging**
